# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qScs
                                 A QGIS plugin
 A QGIS Plugin to Determine Basin Properties for NRCS Peak Flow
Estimation in HEC-HMS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-08
        copyright            : (C) 2022 by sidar
        email                : sidar_qscs@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qScs class from file qScs.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .q_scs import qScs
    return qScs(iface)
